# Release Drafter config: draft release notes from merged PRs
# https://github.com/release-drafter/release-drafter

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## What's Changed
  $CHANGES
